# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=100, verbose_name='Producent')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('description', models.TextField(verbose_name='Opis')),
                ('image', models.FileField(upload_to='Image/%Y-%m-%d', verbose_name='Ścieżka do zdjęcia')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sprzęt',
                'verbose_name_plural': 'Sprzęty',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Aktualności',
                'verbose_name_plural': 'Aktualności',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.IntegerField(default=0, verbose_name='Cena')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pakiet',
                'verbose_name_plural': 'Pakiety',
            },
        ),
    ]
